version: "3"
services:
  openmts-backend:
    image: openmts-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./config/appsettings.Production.json:/app/appsettings.Production.json
      - data-files:/app/files
  openmts-frontend:
    image: openmts-frontend
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  data-files:
