version: "3"
services:
  openmts-server:
    image: alexcharoy/openmts-server
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./configs/server:/app
      - ./data/files:/app/files
  openmts-db: # TODO: db init
    image: timescale/timescaledb:latest-pg11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password # Set password
    volumes:
      - ./data/db:/var/lib/postgresql/data
  openmts-ui:
    image: alexcharoy/openmts-ui
    ports:
      - "8080:80"
  kafka: # TODO: persist data in volume
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_HOST=`docker-machine ip \`docker-machine active\``
      - ADVERTISED_PORT=9092
