version: "3"
services:
  openmts-db:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=openmts
      - POSTGRES_PASSWORD=password # Set password
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./sql:/sql
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on", "-c", "log_disconnections=on", "-c", "log_duration=on", "-c", "log_min_duration_statement=-1", "-c", "log_destination=stderr"]
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka # Set host name/IP
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  openmts:
    image: openmts-complete
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./config/appsettings.Production.json:/app/appsettings.Production.json
      - data-files:/app/files
    depends_on:
      - openmts-db
      - kafka
volumes:
  data-db:
  data-files:
